- name: "Flush existing firewall rules"
  iptables:
    flush: true
  poll: 0

- name: "Remove swapfile from /etc/fstab"
  mount:
    name: swap
    fstype: swap
    state: absent

- name: "Disable swap"
  command: swapoff -a
  when: ansible_swaptotal_mb > 0

- name: "Changing perm of /etc/rc.local +x"
  file:
   dest: /etc/rc.local
   mode: a+x