- name: "[master] - destroy kubernetes"
  shell: |
   kubeadm reset -f
  ignore_errors: True

- name: "[etcd] - destroy etcd"
  shell: |
   docker rm etcd -f
   rm {{ etcd }}/docker-etcd.sh
   docker rm $(docker ps -qa) -f
   rm -rf {{ etcdstorage }}/*
   rm -rf /var/lib/etcd/*
   rm -rf /etc/kubernetes/pki.tgz
  delegate_to: "{{ item }}"
  with_items:
   - "{{ groups['etcd'] }}"
  ignore_errors: True

- name: "[keepalived] - stopped service"
  service:
   name: keepalived
   state: stopped
  ignore_errors: True
  when: inventory_hostname in groups['master']
