---
# tasks file for ansible
- name: "Hosts"
  hosts: all
  become: yes

  vars_files:
  - ../vars/main.yml

  tasks:

    - import_tasks: basic.yml
      tags: basic

    - import_tasks: preparing-redhat.yml
      tags: redhat
      when: ansible_os_family == "RedHat"

    - import_tasks: preparing-ubuntu.yml
      tags: ubuntu
      when: ansible_os_family == "Debian"

    - import_tasks: preparing.yml
      tags: preparing

    - import_tasks: etcd.yml
      tags: etcd

    - import_tasks: master.yml
      tags: master

    - import_tasks: worker.yml
      tags: worker
