- name: "[worker] - kubeadm token create"
  shell: |
   sudo kubeadm join {{ virtualip }}:6443 --token {{ admission_token }} --discovery-token-unsafe-skip-ca-verification
  when: inventory_hostname in groups['worker']
  poll: 0
